In [1]:
from pathlib import Path
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

#Usando Jupyter para análise dos dados antes de usá-los no dash

dataset = Path.joinpath(Path.cwd(),'data', 'dataset_asimov.csv')
df = pd.read_csv(dataset)

df.head()

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
0,Pago,1,Abr,Televisão,R$ 7000000,3,02:00,GK,KJI. L4,A7,Equipe 1,Arthur
1,Pago,10,Ago,Televisão,R$ 11000000,1,02:00,GK,Pre. L8,B13,Equipe 2,Heitor
2,Pago,20,Set,Website,R$ 12000000,3,02:00,GK,Fndn. L5,A1,Equipe 2,Helena
3,Pago,23,Set,Facebook,R$ 15000000,1,02:00,GK,Fndn. L5,A2,Equipe 3,Alice
4,Pago,11,Set,Televisão,R$ 25000000,2,02:00,GK,Fndn. L3,B13,Equipe 4,Theo

In [2]:
#Texto pesa muito mais do que números... converter o que puder para número
##Conversão de meses em números

df.loc[ df['Mês'] == 'Jan', 'Mês'] = 1
df.loc[ df['Mês'] == 'Fev', 'Mês'] = 2
df.loc[ df['Mês'] == 'Mar', 'Mês'] = 3
df.loc[ df['Mês'] == 'Abr', 'Mês'] = 4
df.loc[ df['Mês'] == 'Mai', 'Mês'] = 5
df.loc[ df['Mês'] == 'Jun', 'Mês'] = 6
df.loc[ df['Mês'] == 'Jul', 'Mês'] = 7
df.loc[ df['Mês'] == 'Ago', 'Mês'] = 8
df.loc[ df['Mês'] == 'Set', 'Mês'] = 9
df.loc[ df['Mês'] == 'Out', 'Mês'] = 10
df.loc[ df['Mês'] == 'Nov', 'Mês'] = 11
df.loc[ df['Mês'] == 'Dez', 'Mês'] = 12

df

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
0,Pago,1,4,Televisão,R$ 7000000,3,02:00,GK,KJI. L4,A7,Equipe 1,Arthur
1,Pago,10,8,Televisão,R$ 11000000,1,02:00,GK,Pre. L8,B13,Equipe 2,Heitor
2,Pago,20,9,Website,R$ 12000000,3,02:00,GK,Fndn. L5,A1,Equipe 2,Helena
3,Pago,23,9,Facebook,R$ 15000000,1,02:00,GK,Fndn. L5,A2,Equipe 3,Alice
4,Pago,11,9,Televisão,R$ 25000000,2,02:00,GK,Fndn. L3,B13,Equipe 4,Theo
...,...,...,...,...,...,...,...,...,...,...,...,...
1232,Não pago,18,11,Facebook,R$ 0,2,12:55,NaN,NaN,A1,Equipe 4,Theo
1233,Não pago,24,11,WhatsApp,R$ 0,2,12:55,NaN,NaN,A7,Equipe 2,Heitor
1234,Não pago,9,12,Televisão,R$ 0,1,12:55,NaN,NaN,A4,Equipe 2,Laura
1235,Não pago,11,2,Facebook,R$ 0,2,12:55,NaN,NaN,B18,Equipe 2,Laura
1236,Não pago,12,3,Televisão,R$ 0,2,12:55,NaN,NaN,B18,Equipe 3,Sophia

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1237 entries, 0 to 1236
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Status de Pagamento    1237 non-null   object
 1   Dia                    1237 non-null   int64
 2   Mês                    1237 non-null   object
 3   Meio de Propaganda     1237 non-null   object
 4   Valor Pago             1237 non-null   object
 5   Chamadas Realizadas    1237 non-null   int64
 6   Duração da chamada     1237 non-null   object
 7   Modelo de Treinamento  926 non-null    object
 8   Nivel de Treinamento   926 non-null    object
 9   Código de Área         1237 non-null   object
 10  Equipe                 1237 non-null   object
 11  Consultor              1237 non-null   object
dtypes: int64(2), object(10)
memory usage: 116.1+ KB

In [4]:
#Converter outras colunas para inteiro

df['Chamadas Realizadas'] = df['Chamadas Realizadas'].astype(int)
df['Dia'] = df['Dia'].astype(int)
df['Mês'] = df['Mês'].astype(int)


#Como já haviam valores numéricos misturados com valores com string (R$) na base, foi necessário uma filtragem inicial da coluna 'Valor Pago' e conversão com método apply

#df['Valor Pago'][df['Valor Pago'].astype('object') == True].apply(lambda x: x.str.lstrip('R$ ').astype(int))
df['Valor Pago'] = df['Valor Pago'].str.lstrip('R$ ')
df['Valor Pago'] = df['Valor Pago'].astype(int)

#Conversão dos valores string de Status de Pagamento para valores numéricos
df.loc[df['Status de Pagamento'] == 'Pago', 'Status de Pagamento'] = 1
df.loc[df['Status de Pagamento'] == 'Não pago', 'Status de Pagamento'] = 0

#df['Status de Pagamento'] = df['Status de Pagamento'].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1237 entries, 0 to 1236
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Status de Pagamento    1237 non-null   object
 1   Dia                    1237 non-null   int64
 2   Mês                    1237 non-null   int64
 3   Meio de Propaganda     1237 non-null   object
 4   Valor Pago             1237 non-null   int64
 5   Chamadas Realizadas    1237 non-null   int64
 6   Duração da chamada     1237 non-null   object
 7   Modelo de Treinamento  926 non-null    object
 8   Nivel de Treinamento   926 non-null    object
 9   Código de Área         1237 non-null   object
 10  Equipe                 1237 non-null   object
 11  Consultor              1237 non-null   object
dtypes: int64(4), object(8)
memory usage: 116.1+ KB

In [5]:
df

,Status de Pagamento,Dia,Mês,Meio de Propaganda,Valor Pago,Chamadas Realizadas,Duração da chamada,Modelo de Treinamento,Nivel de Treinamento,Código de Área,Equipe,Consultor
0,1,1,4,Televisão,7000000,3,02:00,GK,KJI. L4,A7,Equipe 1,Arthur
1,1,10,8,Televisão,11000000,1,02:00,GK,Pre. L8,B13,Equipe 2,Heitor
2,1,20,9,Website,12000000,3,02:00,GK,Fndn. L5,A1,Equipe 2,Helena
3,1,23,9,Facebook,15000000,1,02:00,GK,Fndn. L5,A2,Equipe 3,Alice
4,1,11,9,Televisão,25000000,2,02:00,GK,Fndn. L3,B13,Equipe 4,Theo
...,...,...,...,...,...,...,...,...,...,...,...,...
1232,0,18,11,Facebook,0,2,12:55,NaN,NaN,A1,Equipe 4,Theo
1233,0,24,11,WhatsApp,0,2,12:55,NaN,NaN,A7,Equipe 2,Heitor
1234,0,9,12,Televisão,0,1,12:55,NaN,NaN,A4,Equipe 2,Laura
1235,0,11,2,Facebook,0,2,12:55,NaN,NaN,B18,Equipe 2,Laura
1236,0,12,3,Televisão,0,2,12:55,NaN,NaN,B18,Equipe 3,Sophia

In [6]:
#Verificação dos gráficos possíveis de serem gerados

#1) Vendas por equipe

df1 = df.groupby('Equipe')['Valor Pago'].sum().reset_index() ## reset_index() permite mostrar igual a uma tabla

df1

     Equipe  Valor Pago
0  Equipe 1  5288000000
1  Equipe 2  5372000000
2  Equipe 3  2579000000
3  Equipe 4  2751000000

In [7]:
fig1 = go.Figure(go.Bar(
        x=df1['Valor Pago'],
        y=df1['Equipe'],
        orientation='h',
        textposition='auto',
        text=df1['Valor Pago'],
        insidetextfont=dict(family='Times', size=12)
    ))

fig1.show()

In [8]:
#2) Quantidade de chamadas diárias por mês

df2 = df.groupby('Dia')['Chamadas Realizadas'].sum().reset_index()
df2

    Dia  Chamadas Realizadas
0     1                  254
1     2                   60
2     3                   80
3     4                   61
4     5                  108
5     6                   56
6     7                   69
7     8                  127
8     9                   63
9    10                  117
10   11                  309
11   12                  195
12   13                  107
13   14                   92
14   15                   82
15   16                   80
16   17                  102
17   18                   41
18   19                   71
19   20                   86
20   21                   47
21   22                  143
22   23                   36
23   24                   52
24   25                   74
25   26                   70
26   27                   80
27   28                   99
28   29                  109
29   30                  205
30   31                   45

In [9]:
fig2 = go.Figure(go.Scatter(
    x=df2['Dia'], y=df2['Chamadas Realizadas'], mode='lines', fill='tonexty'))

fig2.add_annotation(text='Chamadas Médias por dia do Mês',
                    xref='paper', yref='paper',
                    font=dict(
                            size=20,
                            color='gray',
                        ),
                    align='center', bgcolor='rgba(0,0,0,0.8)',
                    x=0.05, y=0.85, showarrow=False
                    )

fig2.show()

In [10]:
fig2.add_annotation(text=f"Média: {round(df2['Chamadas Realizadas'].mean(), 2)}",
                    xref='paper', yref='paper',
                    font=dict(
                            size=30,
                            color='gray',
                        ),
                    align='center', bgcolor='rgba(0,0,0,0.8)',
                    x=0.05, y=0.55, showarrow=False
                    )

fig2.show()

In [11]:
#Chamadas médias por mês

df4 = df.groupby('Mês')['Chamadas Realizadas'].sum().reset_index()
df4

    Mês  Chamadas Realizadas
0     1                  168
1     2                  164
2     3                   70
3     4                   66
4     5                  180
5     6                  108
6     7                  106
7     8                  211
8     9                  470
9    10                  715
10   11                  539
11   12                  323

In [12]:
fig4 = go.Figure(go.Scatter(
    x=df4['Mês'], y=df4['Chamadas Realizadas'], mode='lines', fill='tonexty'
))

fig4.show()

In [13]:
fig4.add_annotation(text='Chamadas Médias por Mês',
        xref="paper", yref="paper",
        font=dict(
            size=20,
            color='gray'
            ),
        align="center", bgcolor="rgba(0,0,0,0.8)",
        x=0.05, y=0.85, showarrow=False)
fig4.add_annotation(text=f"Média : {round(df4['Chamadas Realizadas'].mean(), 2)}",
        xref="paper", yref="paper",
        font=dict(
            size=30,
            color='gray'
            ),
        align="center", bgcolor="rgba(0,0,0,0.8)",
        x=0.05, y=0.55, showarrow=False)

fig4.show()

In [14]:
#Valores pagos por meio de propaganda

df3 = df.groupby(['Meio de Propaganda', 'Mês'])['Valor Pago'].sum().reset_index()
df3

   Meio de Propaganda  Mês  Valor Pago
0            Facebook    1   334000000
1            Facebook    2   130000000
2            Facebook    3    76000000
3            Facebook    4    90000000
4            Facebook    5   220000000
..                ...  ...         ...
64            Youtube    8    59000000
65            Youtube    9   265000000
66            Youtube   10    58000000
67            Youtube   11   135000000
68            Youtube   12    83000000

[69 rows x 3 columns]

In [15]:
fig3 = px.line(df3, y='Valor Pago', x='Mês', color="Meio de Propaganda")
fig3.show()

In [16]:
#Propaganda em PieChart
df4 = df.groupby('Meio de Propaganda')['Valor Pago'].sum().reset_index()

fig4 = go.Figure()
fig4.add_trace(go.Pie(labels=df4['Meio de Propaganda'], values=df4['Valor Pago'], hole=.7))

fig4.show()

In [17]:
#Ganhos por Mês e segregação por equipe

df.columns

Index(['Status de Pagamento', 'Dia', 'Mês', 'Meio de Propaganda', 'Valor Pago',
       'Chamadas Realizadas', 'Duração da chamada', 'Modelo de Treinamento',
       'Nivel de Treinamento', 'Código de Área', 'Equipe', 'Consultor'],
      dtype='object')

In [18]:
df5 = df.groupby(['Mês', 'Equipe'])['Valor Pago'].sum().reset_index()
df5_group = df.groupby('Mês')['Valor Pago'].sum().reset_index()

In [19]:
df5.head()

   Mês    Equipe  Valor Pago
0    1  Equipe 1   176000000
1    1  Equipe 2   418000000
2    1  Equipe 3   118000000
3    1  Equipe 4   272000000
4    2  Equipe 1   440000000

In [20]:
df5_group.head()

   Mês  Valor Pago
0    1   984000000
1    2  1040000000
2    3   116000000
3    4   538000000
4    5  1158000000

In [21]:
fig5 = px.line(df5, y='Valor Pago', x='Mês', color='Equipe')
fig5.add_trace(go.Scatter(y=df5_group['Valor Pago'], x=df5_group['Mês'], mode='lines+markers', fill='tonexty', fillcolor='rgba(255,0,0,0.2)', name='Total de Vendas'))

fig5.show()

In [22]:
#Pagos e não pagos

df6 = df.groupby('Status de Pagamento')['Chamadas Realizadas'].sum()
df6.head()

Status de Pagamento
0     777
1    2343
Name: Chamadas Realizadas, dtype: int64

In [23]:
fig6 = go.Figure()
fig6.add_trace(go.Pie(labels=['Não Pago', 'Pago'], values=df6, hole=.6))
fig6.show()

In [24]:
#Indicadores - Melhor Consultor

df7 = df.groupby(['Consultor','Equipe'])['Valor Pago'].sum()
df7.sort_values(ascending=False, inplace=True)
df7 = df7.reset_index() #Converte o df em tabela e a coluna de somatório vira o Valor Pago (Total)
df7

   Consultor    Equipe  Valor Pago
0      Laura  Equipe 2  1727000000
1     Helena  Equipe 2  1626000000
2   Bernardo  Equipe 4  1534000000
3    Lorenzo  Equipe 1  1320000000
4     Heitor  Equipe 2  1276000000
5     Sophia  Equipe 3  1205000000
6       Theo  Equipe 4  1177000000
7       Davi  Equipe 1  1066000000
8      Lucas  Equipe 1  1029000000
9       João  Equipe 3   995000000
10    Lorena  Equipe 1   832000000
11    Samuel  Equipe 1   650000000
12   Mathias  Equipe 2   411000000
13     Alice  Equipe 3   379000000
14     Bruno  Equipe 2   332000000
15    Arthur  Equipe 1   329000000
16   Lorenzo  Equipe 4    40000000
17    Sophia  Equipe 1    38000000
18    Heitor  Equipe 1    12000000
19    Helena  Equipe 1    12000000

In [25]:
fig7 = go.Figure()
fig7.add_trace(go.Indicator(mode='number+delta',
                            title={'text': f"<span style= 'font-size:150%'>{df7['Consultor'].iloc[0]} - Top Consultant</span><br><span style='font-size:70%'>Em vendas - em relação à média</span><br>"},
                            value = df7['Valor Pago'].iloc[0],
                            number={'prefix':'R$'},
                            delta={'relative':True,'valueformat':'.1%', 'reference':df7['Valor Pago'].mean()}
                            ))

fig7.show()

In [26]:
#TOP 5 - Equipe e consultores
#Melhor Equipe

df8 = df.groupby('Equipe')['Valor Pago'].sum()
df8.sort_values(ascending=False, inplace=True)
df8 = df8.reset_index()
df8

     Equipe  Valor Pago
0  Equipe 2  5372000000
1  Equipe 1  5288000000
2  Equipe 4  2751000000
3  Equipe 3  2579000000

In [27]:
fig8 = go.Figure()
fig8.add_trace(go.Indicator(mode='number+delta',
                            title={'text': f"<span style= 'font-size:150%'>{df8['Equipe'].iloc[0]} - Top Team</span><br><span style='font-size:70%'>Em vendas - em relação à média</span><br>"},
                            value = df8['Valor Pago'].iloc[0],
                            number={'prefix':'R$'},
                            delta={'relative':True,'valueformat':'.1%', 'reference':df8['Valor Pago'].mean()}
                            ))

fig8.show()

In [28]:
#Ganhos totais

fig9 = go.Figure()
fig9.add_trace(go.Indicator(mode='number',
                            title={'text': f"<span style= 'font-size:150%'>Valor Total</span><br><span style='font-size:70%'>Em Reais</span><br>"},
                            value = df['Valor Pago'].sum(),
                            number={'prefix':'R$'}
                            ))

fig9.show()

In [29]:
#Total de chamadas

fig10 = go.Figure()
fig10.add_trace(go.Indicator(mode='number',
                            title={'text': f"<span style= 'font-size:150%'>Chamadas Realizadas</span>"},
                            value = len(df[df['Status de Pagamento'] == 1])
                            ))

fig10.show()

In [30]:
#Top Consultor por Equipe e valores de renda

df12 = df.groupby(['Equipe', 'Consultor'])['Valor Pago'].sum().reset_index()
df12

      Equipe Consultor  Valor Pago
0   Equipe 1    Arthur   329000000
1   Equipe 1      Davi  1066000000
2   Equipe 1    Heitor    12000000
3   Equipe 1    Helena    12000000
4   Equipe 1    Lorena   832000000
5   Equipe 1   Lorenzo  1320000000
6   Equipe 1     Lucas  1029000000
7   Equipe 1    Samuel   650000000
8   Equipe 1    Sophia    38000000
9   Equipe 2     Bruno   332000000
10  Equipe 2    Heitor  1276000000
11  Equipe 2    Helena  1626000000
12  Equipe 2     Laura  1727000000
13  Equipe 2   Mathias   411000000
14  Equipe 3     Alice   379000000
15  Equipe 3      João   995000000
16  Equipe 3    Sophia  1205000000
17  Equipe 4  Bernardo  1534000000
18  Equipe 4   Lorenzo    40000000
19  Equipe 4      Theo  1177000000

In [37]:
df13 = df.groupby(['Equipe', 'Consultor'])['Valor Pago'].sum()
df13 = df13.sort_values(ascending=False)
df13 = df13.groupby('Equipe').head(1).reset_index() #Permite pegar os melhores vendedores de cada equipe (groupby de equipe + head(1) de cada)
df13

     Equipe Consultor  Valor Pago
0  Equipe 2     Laura  1727000000
1  Equipe 4  Bernardo  1534000000
2  Equipe 1   Lorenzo  1320000000
3  Equipe 3    Sophia  1205000000

In [38]:
fig13 = go.Figure(go.Pie(labels=df13['Consultor'] + ' - ' + df13['Equipe'], values=df13['Valor Pago'], hole=.6))
fig13.show()

In [39]:
fig14 = go.Figure(go.Bar(x=df13['Consultor'], y=df13['Valor Pago'], textposition='auto', text=df13['Valor Pago']))
fig14.show()