# Selecionando colunas e filtrando linhas

In [1]:
import pandas as pd

## Selecionando colunas

In [2]:
data = {'Nome': ['Adriano', 'Rodrigo', 'Juliano', 'Mateus', 'Luiza', 'Rodrigo', 'Ayres', 'Aninha'],
		'Sobrenome': ['Soares', 'Tadewald', 'Faccioni', 'Kienzle', 'Cherobini', 'Vanzelotti', 'Júnior', 'Tadewald'],
		'Idade Atual': [31, 31, 25, 35, 22, 21, 28, 20],
		}

df = pd.DataFrame(data)
df.Sobrenome

0        Soares
1      Tadewald
2      Faccioni
3       Kienzle
4     Cherobini
5    Vanzelotti
6        Júnior
7      Tadewald
Name: Sobrenome, dtype: object

In [3]:
colunas = [col for col in df.columns if not col in ['Sobrenome']]
df[colunas]

      Nome  Idade Atual
0  Adriano           31
1  Rodrigo           31
2  Juliano           25
3   Mateus           35
4    Luiza           22
5  Rodrigo           21
6    Ayres           28
7   Aninha           20

## Filtrando por indexação (.iloc)

In [4]:
#seleção da linha 1 a 3 (posição vetorial)
df.iloc[1:3]

      Nome Sobrenome  Idade Atual
1  Rodrigo  Tadewald           31
2  Juliano  Faccioni           25

In [6]:
#seleção da linha 3 em diante, pegando a coluna 0
df.iloc[3:, 0]

3     Mateus
4      Luiza
5    Rodrigo
6      Ayres
7     Aninha
Name: Nome, dtype: object

In [7]:
#seleção da linha 3 em diante, pegando a coluna 0 e 2
df.iloc[3:, 0:1]

      Nome
3   Mateus
4    Luiza
5  Rodrigo
6    Ayres
7   Aninha

## Filtrando por condições (.loc)

In [8]:
df[df['Nome'] == 'Rodrigo']

      Nome   Sobrenome  Idade Atual
1  Rodrigo    Tadewald           31
5  Rodrigo  Vanzelotti           21

In [12]:
df.loc[df['Nome'] == 'Rodrigo', ['Sobrenome']]

    Sobrenome
1    Tadewald
5  Vanzelotti

## Filtrando por múltiplas condições

In [15]:
df.loc[((df['Nome'] == 'Rodrigo') & (df['Sobrenome'] == 'Tadewald')), ['Sobrenome']]

  Sobrenome
1  Tadewald

In [16]:
df.loc[((df['Nome'] == 'Rodrigo') | (df['Nome'] == 'Juliano')), ['Sobrenome', 'Idade Atual']]

    Sobrenome  Idade Atual
1    Tadewald           31
2    Faccioni           25
5  Vanzelotti           21

## Filtrando por lista de valores (.isin)

In [17]:
nomes_filtro = ['Rodrigo', 'Juliano']
df.loc[df['Nome'].isin(nomes_filtro)]

      Nome   Sobrenome  Idade Atual
1  Rodrigo    Tadewald           31
2  Juliano    Faccioni           25
5  Rodrigo  Vanzelotti           21

In [19]:
df['Nome'].str.contains('Adri')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Nome, dtype: bool

In [18]:
df.loc[df['Nome'].str.contains('Adri')]

      Nome Sobrenome  Idade Atual
0  Adriano    Soares           31